# -*- coding: utf-8 -*-
"""exp4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fgj9cZ6NdIYquU79NTxKI6Y1_gDkL06S
"""

import pandas as pd
data=pd.read_csv("heart_disease_uci.csv")
print("Data:")
print(data.head())

print("Information about dataset:\n")
print(data.info())

print("Number of columns and rows:\n")
print(data.shape)

print("Basic Statistics on numerical colums:\n")
print(data.describe())

print("Number of null values in each column:\n")
print(data.isnull().sum())

print("How colums categorized:\n")
print(data['sex'].value_counts())
print("\n")
print(data['cp'].value_counts())
print("\n")
print(data['thalch'].value_counts())
print("\n")
print(data['dataset'].value_counts())
print("\n")

print("How many unique values:\n")
print(data.nunique())